# HTTP服务
[server]
	Address     = ":8080"
	ServerAgent = "gf-extend"

# 数据库
[database]
    [database.default]
        link = "sqlite:./db/sqlite3.db"
        debug = true
    [database.casbin]
        link = "sqlite:./db/sqlite3.db"
        debug = true
    [database.mysql]
        link = "mysql:root:root@tcp(127.0.0.1:3306)/casbin"
        debug = true
